### ISSUE TITLE
Skein Problem

### ISSUE THREAD

**Issue by RedwoodNational** [QRCS-CORP/CEX#2]
Skein family digests on empty messages are incorrect
I receive this digest with Skein256 on empty message:
1C98682567C95BC38F9CFCD54A769259D3B071F8BBE80EA5394F1B3952144055
But Wiki writes that it should be:
C8877087DA56E072870DAA843F176E9453115929094C3A40C463A196C29BF7BA

**Comment by QRCS-CORP** [comment]
Congrats.. this is the first reported bug found in this library!
I have fixed the issue, updated all Skein modes, and added the empty string to the list of test vectors.
Thanks for looking..

JGU
